// Data for Nakshatra Catering & Event site

window.NAKSHATRA_DATA = {

  biryaniVariants: [
    { en: "Mutton Biryani",    ml: "ആട്ടിറച്ചി ബിരിയാണി" },
    { en: "Chicken Biryani",   ml: "കോഴി ബിരിയാണി" },
    { en: "Beef Biryani",      ml: "ഇറച്ചി ബിരിയാണി" },
    { en: "Prawn Biryani",     ml: "ചെമ്മീൻ ബിരിയാണി" },
    { en: "Fish Biryani",      ml: "മത്സ്യ ബിരിയാണി" },
    { en: "Egg Biryani",       ml: "മുട്ട ബിരിയാണി" },
  ],

  sadyaItems: [
    "Choru (Kerala matta rice)",
    "Parippu curry",
    "Sambar",
    "Rasam",
    "Avial",
    "Thoran (4 varieties)",
    "Olan",
    "Kalan",
    "Kootukari",
    "Erissery",
    "Pachadi & Kichadi",
    "Naranga curry",
    "Inji puli",
    "Banana chips",
    "Sharkara varatti",
    "Pappadam",
    "Banana",
    "Pickle (mango & lime)",
    "Buttermilk",
    "Paal payasam",
    "Ada pradhaman",
    "Pazha pradhaman",
    "Boli & Pal payasam",
    "Curd rice",
    "Sambharam",
    "Banana leaf",
  ],

  specialties: [
    {
      title: "Kalyana Sadya",
      ml: "കല്യാണ സദ്യ",
      img: "images/sadya-overhead.png",
      desc: "26 traditional dishes served the proper way — on banana leaf, in correct sequence, every grain accounted for.",
    },
    {
      title: "The Biryani",
      ml: "ബിരിയാണി",
      img: "images/biryani-mutton.png",
      desc: "What put us on the map. Mutton, chicken, beef, prawn — slow-cooked rice that holds its grain.",
    },
    {
      title: "Multi-cuisine Buffet",
      ml: "ബുഫെ",
      img: "images/spread-tray.png",
      desc: "South Indian, North Indian, Chinese, Continental, BBQ counters. Built around your guest mix.",
    },
    {
      title: "Tea & Payasam Station",
      ml: "ചായ • പായസം",
      img: "images/payasam.png",
      desc: "Live chai, filter coffee, four payasam varieties. The way Kerala finishes a meal.",
    },
  ],

  menus: {
    sadya: {
      label: "Sadya",
      ml: "സദ്യ",
      items: [
        { en: "Paal Payasam",        ml: "പാൽ പായസം",       tag: "Signature" },
        { en: "Ada Pradhaman",       ml: "അട പ്രഥമൻ",        tag: "Sweet" },
        { en: "Avial",               ml: "അവിയൽ",            tag: "Veg" },
        { en: "Olan",                ml: "ഓലൻ",              tag: "Veg" },
        { en: "Erissery",            ml: "എരിശ്ശേരി",        tag: "Veg" },
        { en: "Sambar",              ml: "സാമ്പാർ",          tag: "Veg" },
        { en: "Kalan",                ml: "കാളൻ",             tag: "Veg" },
        { en: "Naranga Curry",       ml: "നാരങ്ങ കറി",      tag: "Pickle" },
        { en: "Sharkara Varatti",    ml: "ശർക്കരവരട്ടി",  tag: "Side" },
        { en: "Inji Puli",           ml: "ഇഞ്ചി പുളി",       tag: "Pickle" },
      ],
    },
    biryani: {
      label: "Biryani",
      ml: "ബിരിയാണി",
      items: [
        { en: "Thalassery Mutton Biryani", ml: "തലശ്ശേരി ആട്ടിറച്ചി",   tag: "Signature", desc: "Khyma rice, slow-cooked goat" },
        { en: "Chicken Dum Biryani",       ml: "കോഴി ദം",                  tag: "Bestseller" },
        { en: "Beef Biryani",              ml: "ഇറച്ചി ബിരിയാണി",       tag: "Kochi style" },
        { en: "Prawn Biryani",             ml: "ചെമ്മീൻ ബിരിയാണി",     tag: "Seafood" },
        { en: "Fish Biryani",              ml: "മത്സ്യ ബിരിയാണി",      tag: "Seafood" },
        { en: "Vegetable Biryani",         ml: "പച്ചക്കറി ബിരിയാണി",   tag: "Veg" },
        { en: "Egg Biryani",               ml: "മുട്ട ബിരിയാണി",       tag: "Classic" },
        { en: "Kuzhimanthi (Chicken)",     ml: "കുഴിമന്തി",                tag: "Arabic" },
      ],
    },
    seafood: {
      label: "Sea Food",
      ml: "മത്സ്യം",
      items: [
        { en: "Karimeen Pollichathu",   ml: "കരിമീൻ പൊള്ളിച്ചത്",   tag: "Signature", desc: "Pearl spot grilled in banana leaf" },
        { en: "Meen Mulakittathu",      ml: "മീൻ മുളകിട്ടത്",         tag: "Curry" },
        { en: "Squid Roast",            ml: "കൂന്തൽ റോസ്റ്റ്",         tag: "Dry" },
        { en: "Prawn Roast",            ml: "ചെമ്മീൻ റോസ്റ്റ്",      tag: "Dry" },
        { en: "Fish Fry (Pomfret)",     ml: "വറുത്ത മത്സ്യം",         tag: "Fry" },
        { en: "Mathi Fry",              ml: "മത്തി",                       tag: "Fry", desc: "Sardines, masala-coated" },
        { en: "Crab Roast",             ml: "ഞണ്ട് റോസ്റ്റ്",          tag: "Dry" },
        { en: "Fish Moilee",            ml: "മീൻ മൊളീ",               tag: "Curry" },
      ],
    },
    meat: {
      label: "Chicken & Mutton",
      ml: "ഇറച്ചി",
      items: [
        { en: "Chicken Roast",          ml: "കോഴി റോസ്റ്റ്",          tag: "Dry" },
        { en: "Kerala Mutton Curry",    ml: "ആട്ടിറച്ചി കറി",         tag: "Curry" },
        { en: "Mutton Pepper Fry",      ml: "ആട്ടിറച്ചി കുരുമുളക്", tag: "Dry" },
        { en: "Chicken 65",             ml: "ചിക്കൻ 65",                tag: "Starter" },
        { en: "Beef Ularthiyathu",      ml: "ഇറച്ചി ഉലർത്തിയത്",   tag: "Signature", desc: "Slow-roasted with coconut chips" },
        { en: "Chicken Varutharachathu",ml: "വറുത്തരച്ച കോഴി",     tag: "Curry" },
        { en: "Chilli Chicken",         ml: "ചില്ലി ചിക്കൻ",          tag: "Indo-Chinese" },
        { en: "Mutton Biryani Stew",    ml: "ആട് സ്റ്റൂ",              tag: "Stew" },
      ],
    },
    veg: {
      label: "Vegetarian",
      ml: "സസ്യാഹാരം",
      items: [
        { en: "Thoran (Cabbage, Beans, Beetroot)", ml: "തോരൻ",          tag: "Veg" },
        { en: "Vegetable Stew",         ml: "സ്റ്റൂ",                   tag: "Curry" },
        { en: "Paneer Butter Masala",   ml: "പനീർ",                     tag: "North Indian" },
        { en: "Gobi Manchurian",        ml: "ഗോബി",                     tag: "Indo-Chinese" },
        { en: "Veg Kurma",              ml: "കുറുമ",                    tag: "Curry" },
        { en: "Aloo Gobi",              ml: "ആലൂ ഗോബി",                tag: "North Indian" },
        { en: "Mushroom Pepper Fry",    ml: "കൂൺ കുരുമുളക്",        tag: "Dry" },
        { en: "Veg Fried Rice",         ml: "ഫ്രൈഡ് റൈസ്",            tag: "Rice" },
      ],
    },
    sweets: {
      label: "Sweets",
      ml: "മധുരം",
      items: [
        { en: "Paal Payasam",           ml: "പാൽ പായസം",              tag: "Signature" },
        { en: "Ada Pradhaman",          ml: "അട പ്രഥമൻ",                tag: "Classic" },
        { en: "Pazha Pradhaman",        ml: "പഴം പ്രഥമൻ",              tag: "Banana" },
        { en: "Parippu Pradhaman",      ml: "പരിപ്പ് പ്രഥമൻ",        tag: "Lentil" },
        { en: "Carrot Halwa",           ml: "ഗജര ഹൽവ",                tag: "North Indian" },
        { en: "Gulab Jamun",            ml: "ഗുലാബ് ജാമൂൻ",          tag: "Bestseller" },
        { en: "Kulfi (Pista, Mango)",   ml: "കുൽഫി",                    tag: "Frozen" },
        { en: "Boli & Payasam",         ml: "ബോളി",                     tag: "Combo" },
      ],
    },
  },

  services: [
    { ml: "ഭക്ഷണം",   title: "Catering",         desc: "Veg & non-veg, sadya through buffet. From 250 to 2,500 guests.",                  glyph: "❀" },
    { ml: "അലങ്കാരം", title: "Decoration",       desc: "Mandapam, stage, entrance arches, floral installations.",                        glyph: "✿" },
    { ml: "ഫോട്ടോ",  title: "Photography",      desc: "Stills, candids, traditional. Same team for ceremony and reception.",            glyph: "◉" },
    { ml: "വീഡിയോ",  title: "Videography",      desc: "Cinematic full-day coverage. Drone available on request.",                       glyph: "▶" },
    { ml: "വാഹനം",   title: "Car Decoration",   desc: "Bride & groom vehicles, floral, garlands, ribbons.",                              glyph: "✦" },
  ],

  testimonials: [
    {
      stars: 5,
      quote: "Must-visit for food enthusiasts. The biryani won't disappoint — we ordered for 800 people and not a single complaint.",
      name: "Anand R.",
      meta: "Wedding · Kalamassery · 800 guests",
      source: "Google review",
    },
    {
      stars: 5,
      quote: "Distinctive assortment of biryani. Proper cleanliness and hygiene maintained throughout the event — visible from prep to plating.",
      name: "Lakshmi M.",
      meta: "Engagement · Vyttila · 320 guests",
      source: "Google review",
    },
    {
      stars: 5,
      quote: "We picked Nakshatra because my grandmother insisted — they did her brother's wedding in 2008. Same care, same payasam.",
      name: "Sreejith P.",
      meta: "Kalyanam · Tripunithura · 1,400 guests",
      source: "WedMeGood",
    },
  ],

  timeline: [
    { yr: "2002", h: "Nakshatra opens",     p: "Founded behind Ponnurunni Temple, Vyttila. First wedding: 240 plates, all sadya." },
    { yr: "2008", h: "First 1,000-plate event", p: "A Kalamassery wedding put the kitchen and the biryani on Kochi's map." },
    { yr: "2014", h: "Full event package",  p: "Decoration, photography, car decor brought in-house — one number for everything." },
    { yr: "2019", h: "Listed Top 5 Kochi",  p: "Featured by city aggregators alongside Kochi's premium caterers." },
    { yr: "2024", h: "1,500+ Google reviews", p: "Crossed 1,581 reviews at 4.3★ — built one happy family at a time." },
  ],

  galleryImages: [
    { src: "images/biryani-mutton.png",     cat: "biryani",  cls: "tall", cap: "Mutton Biryani",       ml: "തലശ്ശേരി" },
    { src: "images/sadya-overhead.png",     cat: "sadya",    cls: "",     cap: "Sadya — overhead",     ml: "സദ്യ" },
    { src: "images/fish-grilled.png",       cat: "seafood",  cls: "",     cap: "Karimeen Pollichathu", ml: "കരിമീൻ" },
    { src: "images/biryani-mound.png",      cat: "biryani",  cls: "",     cap: "Chicken Biryani",      ml: "കോഴി" },
    { src: "images/chicken-dry-leaf.png",   cat: "meat",     cls: "",     cap: "Chicken Roast",        ml: "റോസ്റ്റ്" },
    { src: "images/sadya-plated.png",       cat: "sadya",    cls: "",     cap: "Banana leaf, full",    ml: "സദ്യ" },
    { src: "images/fish-fry-2.png",         cat: "seafood",  cls: "tall", cap: "Fish Fry",             ml: "മത്സ്യം" },
    { src: "images/spread-tray.png",        cat: "snacks",   cls: "",     cap: "Mixed tray",           ml: "സ്റ്റാർട്ടർ" },
    { src: "images/payasam.png",            cat: "sweets",   cls: "",     cap: "Paal Payasam",         ml: "പായസം" },
    { src: "images/chilli-masala.png",      cat: "snacks",   cls: "",     cap: "Chilli Masala",        ml: "മസാല" },
    { src: "images/thoran.png",             cat: "sadya",    cls: "",     cap: "Thoran",               ml: "തോരൻ" },
    { src: "images/sardines-fried.png",     cat: "seafood",  cls: "",     cap: "Mathi Fry",            ml: "മത്തി" },
    { src: "images/fish-grilled-2.png",     cat: "seafood",  cls: "",     cap: "Grilled fish",         ml: "മത്സ്യം" },
    { src: "images/manchurian.png",         cat: "snacks",   cls: "",     cap: "Gobi Manchurian",      ml: "ഗോബി" },
    { src: "images/chicken-roast.png",      cat: "meat",     cls: "",     cap: "Chicken plate",        ml: "കോഴി" },
    { src: "images/sadya-sambar.png",       cat: "sadya",    cls: "",     cap: "Sadya, served",        ml: "സദ്യ" },
  ],

  eventTypes: [
    { id: "wedding",   title: "Wedding",          ml: "കല്യാണം" },
    { id: "reception", title: "Reception",        ml: "സ്വീകരണം" },
    { id: "engagement",title: "Engagement",       ml: "നിശ്ചയം" },
    { id: "housewarm", title: "House Warming",    ml: "ഗൃഹപ്രവേശം" },
    { id: "birthday",  title: "Birthday",         ml: "ജന്മദിനം" },
    { id: "corporate", title: "Corporate Event",  ml: "—" },
  ],

  guestSizes: ["50–150", "150–300", "300–600", "600–1,200", "1,200–2,000", "2,000+"],
};
